[workspace]
resolver = "3"
members = [
    "crates/*",
    "dexter-python"
]
default-members = [
    "crates/*",
]

[workspace.dependencies]
ndarray = "0.17.1"
thiserror = "2.0.17"
criterion = "0.7.0"
safe_unwrap = "0.4.1"
rsl-interpolation = { git = "https://github.com/George-Tsiamasiotis/rsl-interpolation.git", branch = "dev-0.1.16-pre", features = ["openblas-system"]}

config = { path = "crates/config", default-features = false }
utils = { path = "crates/utils", default-features = false }

common = { path = "crates/common", default-features = false }
equilibrium = { path = "crates/equilibrium", default-features = false }
particle = { path = "crates/particle", default-features = false }
heap = { path = "crates/heap", default-features = false }
dexter = { path = "crates/dexter", default-features = false }

[workspace.package]
authors = ["George Tsiamasiotis"]
edition = "2024"
rust-version = "1.91.1"
license = "GPL-3.0-only"
homepage = "https://github.com/George-Tsiamasiotis/DEXTER"
repository = "https://github.com/George-Tsiamasiotis/DEXTER"
documentation = "https://github.com/George-Tsiamasiotis/DEXTER"
description = "Calculations and simulations in reconstructed equilibria of toroidal fusion devices."

[profile.release-lto]
inherits = "release"
opt-level = 3
debug = "none"
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false
codegen-units = 1

# Bevy tip

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
