[project]
name = "dexter"
version = "0.1.2-pre.8"
description = "Calculations and simulations in reconstructed equilibria of toroidal fusion devices."
readme = "README.md"
authors = [
    { name = "George-Tsiamasiotis", email = "gt.develop@protonmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
]

[tool.maturin]
module-name = "dexter._core"
python-packages = ["dexter"]
python-source = "./dexter-python/"
manifest-path="./dexter-python/Cargo.toml"
# This also seems to solver maturin's and rust-analyzer's cache invalidation
# problem which forces pyo3 and rust-numpy to recompile every time
profile = "release"
editable-profile = "release"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "ipython>=9.6.0",
    "maturin-import-hook>=0.3.0",
    "patchelf>=0.17.2.4",
    "pygobject>=3.54.5",
    "pytest>=8.4.2",
    "mypy>=1.18.2",
    "xarray>=2025.10.1",
    "netcdf4>=1.7.3",
    "semver>=3.0.4",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.0",
    "mkdocstrings[python]>=1.0.0",
]

[tool.pytest.ini_options]
testpaths = ["./dexter-python/pytests", "./dexter-python/dexter/", "./docs/docs/"] # Run from workspace root
addopts = "--durations 2 --doctest-glob='*.md' --doctest-glob='*.pyi'"

[project.scripts]
# NetCDF handling
npz_to_netcdf = "dexter.scripts:npz_to_netcdf"
stub_npz = "dexter.scripts:stub_npz"
# Plots
qfactor_plot = "dexter.scripts:qfactor_plot"
currents_plot = "dexter.scripts:currents_plot"
bfield_plot = "dexter.scripts:bfield_plot"
flux_surfaces_plot= "dexter.scripts:flux_surfaces_plot"
harmonic_plot = "dexter.scripts:harmonic_plot"
